---
abstract: 'Sim::OPT it a tool for detailed metadesign managing parametric explorations through the ESP-r building performance simulation platform and performing optimization by block coordinate descent.'
author:
  - 'Gian Luca Brunetti <gianluca.brunetti@polimi.it>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sim-OPT
no_index:
  directory:
    - t
    - inc
requires:
  List::MoreUtils: '0.01'
version: v0.39.6_7
